---
# tasks/ensure-roles.yml

- name: Ensure Base | Ensure roles
  environment: "{{ proxy_env }}"
  block:
    - name: Install pip
      ansible.builtin.include_role:
        name: geerlingguy.pip

    - name: Install docker
      ansible.builtin.include_role:
        name: geerlingguy.docker
      vars:
        docker_install_compose: true
        docker_compose_path: /usr/local/bin/docker-compose
        docker_daemon_options: "{{ {'default-address-pools': docker_address_pools} if (docker_address_pools | default([]) | length) > 0 else {} }}"

    - name: Install manage_traefik
      ansible.builtin.include_role:
        name: gesinn.manage_traefik
