---
# tasks/main.yml

# Default entry point for the role.
#
# Existing projects may still call specific task files via tasks_from:
#
# tasks:
#   - name: Ensure Base | Ensure roles
#     ansible.builtin.include_role:
#       name: gesinn.manage_base
#       tasks_from: ensure-roles.yml

- name: Ensure Base | Ensure base roles
  ansible.builtin.import_tasks: ensure-roles.yml


- name: Ensure Base | Check Docker network sanity
  ansible.builtin.import_tasks: check-docker-networks.yml
  when: manage_base_docker_network_check | default(true)


- name: Ensure Base | Configure journald retention
  ansible.builtin.import_tasks: configure-journald.yml
  when: manage_base_configure_journald | default(true)


- name: Ensure Base | Setup proxy
  ansible.builtin.import_tasks: setup-proxy.yml
  when: manage_base_setup_proxy | default(false)
