- name: Ensure Base | Setup docker https_proxy if required
  become: true
  environment: "{{ proxy_env }}"
  when:
    - proxy_env.http_proxy is defined
    - proxy_env.https_proxy is defined
  block:
    - name: Ensure Base | Setup proxy | Create /etc/systemd/system/docker.service.d
      ansible.builtin.file:
        path: /etc/systemd/system/docker.service.d
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Ensure Base | Setup proxy | Set docker http/https_proxy
      ansible.builtin.copy:
        dest: /etc/systemd/system/docker.service.d/http-proxy.conf
        owner: root
        group: root
        mode: "0644"
        content: |
          [Service]
          Environment="HTTP_PROXY={{ proxy_env.http_proxy }}"
          Environment="HTTPS_PROXY={{ proxy_env.https_proxy }}"
      notify: Restart docker

    - name: Ensure Base | Setup proxy | Create /root/.docker directory
      ansible.builtin.file:
        path: /root/.docker
        state: directory
        owner: root
        group: root
        mode: '0700'

    - name: Ensure Base | Setup proxy | Create config.json
      ansible.builtin.template:
        src: docker/config.json
        dest: /root/.docker/config.json
        owner: root
        group: root
        mode: "0600"
